README.adoc
src/main/groovy/io/gatling/gradle/JvmConfigurable.groovy

Motivation:
In Gatling 3.4.0, we are fixing our set of JVM options and System props.
Modifications:
Use the same set as gatling.sh, gatling.bat, gatling-maven-plugin, gatling-sbt and FrontLine.
Result:
Better default JVM tuning for better performance

Update default JVM options and System props

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Motivation:
* GatlingPlugin doesn't need to store a reference to the Project
* GatlingPluginExtension doesn't need Project at all
Modifications:
* Pass Project to private GatlingPlugin methods.
* Stop passing Project to GatlingPluginExtension
Result:
Less dead code

Minor clean up: stop storing project

---

src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/main/groovy/io/gatling/gradle/LogHttp.groovy
src/main/groovy/io/gatling/gradle/LogbackConfigTaskAction.groovy
src/test/groovy/func/LogbackConfigTaskActionTest.groovy

Motivation:
In all other launchers, we document a special slf4j logger to enable logging on either all or failed HTTP traffic.
The standard approach with gatling-gradle-plugin is to have it generate the logback config file, hence users are not aware of this logging option.
Modifications:
Introduce a new extension property named `logHttp` that can take the values `NONE`, `ALL` and `FAILURES` that would set the HTTP logger level respectively to the same as root, TRACE and DEBUG.
Result:
gatling-gradle-plugin users now have a convenient option for tuning HTTP logging level.

Introduce logHttp extension property to tune HTTP logging in generated logback config file, close gatling/gatling#3949

---

gradle/wrapper/gradle-wrapper.properties
src/test/groovy/func/GradleCompatibilitySpec.groovy
src/test/groovy/unit/GatlingPluginTest.groovy

Motivation:
We want to make sure we support the latest stable release, which is 6.6.1 as of now.
We also want to be notified of deprecations so we can anticipate on the required changes in order to support the next major release (gradle 7).
Modifications:
* build the plugin with latest 6.6.1 as of now
* add 6.6.1 to the versions tested in GradleCompatibilitySpec
Result:
Plugin is now built and tested against the latest stable release.

Chore: Upgrade gradle to 6.6.1

---

.github/workflows/test-only.yml
README.adoc

This is just a _proposal_, until the whole doc wil be migrated to Gatling docs repo.
As far as my PR to demo repo was accepted, I considered that main plugin docs ( regardless where they located) 
should be reduced a little bit.
Plz suggest.
relates gatling/gatling#3953
PS: also I've added some sane exclude for GitHub worflows

chore(docs): link to demo repo

---

.github/workflows/test-only.yml
README.adoc

* more excludes for GG action workflows
* fixed broken layout
* added logHttp ( i remember it was not added because no need to update this README anymore, but I was afraid it maybe lost during migration to Gatling docs system)

chore(docs): minor fixes to readme

---

src/test/groovy/unit/LogbackConfigTaskTest.groovy

Motivation:
Previous commit did fix the issue but was missing tests proving it.
Modifications:
Add tests proving logback.xml file gets generated even though resources is empty or missing.
Result:
Fix proven

Add tests providing logback.xml file is generated even though resources is empty or missing

---

README.adoc
src/main/groovy/io/gatling/gradle/JvmConfigurable.groovy

Motivation:
It's probably not safe to enforce IPv6 over IPv4 and there's no clear benefits.
Modification:
Revert java.net.preferIPv6Addresses change introduced in 456e22b.
Result:
Use JVM's default wrt net behavior

We should stick to preferIPv6Addresses's default (false)

---

README.adoc
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/test/groovy/helper/GatlingSpec.groovy
src/test/resources/gatling-debug/src/gatling/scala/GatlingDebugSimulation.scala

Motivation:
Edit @slandelle: Gatling 3.4.0 is about to be released (binaries are available on maven central but official announcement will only happen tomorrow once everything is online, FrontLine included)
Modifications:
* 3.4.0 in documentation
* 3.4.0 in gatling dependencies
Result:
Ready for the release

Prepare release 3.4.0

---

.github/workflows/publish.yml

Motivation:
As warned by github [1], the set-env is not possible anymore
Modifications:
* replace olegtarasov/get-tag by little-core-labs/get-git-tag github action
Result:
The publish action will not use environment variable anymore
Refs:
[1]: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
[2]: https://github.com/olegtarasov/get-tag/issues/14

Avoid using environment variable

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/test/resources/gradle-layout/src/gatling/scala/computerdatabase/BasicSimulation.scala

gatling/gatling#4040
Motivation:
By default, this plugin should be compatible with the tutorial examples.
Modifications:
Add default scala compiler options.
Result:
* By default, user are now able to:
- use postfix notation `-language:postfixOps`
- use implicit conversions `-language:implicitConversions`
- see warning when using deprecated feature `-deprecation`
- see help and location when using a feature that requires explicit import `-feature`
* The user may override that configuration. Sample:
```groovy
tasks.getByName("compileGatlingScala") {
scalaCompileOptions.with {
additionalParameters = ["-target:jvm-1.8"]
}
}
```

Add scala compiler options, closes gatling/gatling#4040

---

src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/main/groovy/io/gatling/gradle/GatlingRunTask.groovy
src/main/groovy/io/gatling/gradle/JvmConfigurable.groovy
src/test/groovy/func/WhenRunSimulationSysPropsJvmArgsSpec.groovy

This was modeled on the way [environment variables work with the JavaExec task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:environment).  (The property is called "environment" and assigning a map doesn't clobber existing variables but only sets additional variables.)  It was also modeled on the way the plugin handles system properties: environment variables set using the gatling extension are overridden by variables set in gatlingRun tasks.

Permit the setting of environment variables

---

src/main/groovy/io/gatling/gradle/GatlingRunTask.groovy
src/main/groovy/io/gatling/gradle/JvmConfigurable.groovy
src/main/groovy/io/gatling/gradle/LogbackConfigTask.groovy
src/test/groovy/func/GradleCompatibilitySpec.groovy

Since Gradle 7 Tasks with getters/properties throw errors if they are not properly annotated.
This fixes gatling/gatling/issues/4068

Add missing Gradle UP-TO-DATE check annotations to support Gradle 7

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterprisePublishTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Upload artifact from gradle plugin on Gatling Enterprise
* Use `gatling-enterprise-plugin-commons` enterprise client to upload
* Add `gatlingEnterprisePublish` goal to upload package
**Result:**
Upload using `gatlingEnterprisePublish`.
Need configuration of `packageId` or `apiToken`.

Gatling Enterprise upload package, closes MISC-231

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/test/groovy/func/GradleCompatibilitySpec.groovy
src/test/groovy/func/WhenPackageSpec.groovy

I think the code with `conventionMapping` is outdated? It certainly doesn't work in my tests using Gradle 7. But anyway, we can directly configure the classifier on the `ShadowJar` task which we extend.

Properly set the 'tests' classifier for gatlingEnterprisePackage task

---

src/main/groovy/io/gatling/gradle/GatlingRunTask.groovy
src/test/groovy/func/WhenRunSimulationSpec.groovy

Motivation:
Most users don't understand why their tests does not run when calling gatlingRun a second time in a row.
Modifications:
GatlingRun task is never up to date
Result:
We can launch simulation as many times in a row we want without weird arguments or specific configuration.

feat: avoid caching simulations result

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/test/groovy/unit/GatlingRunTaskTest.groovy

Allow to start a simulation configured with a non-discovered class name,
by overriding the value based on plugin configuration or by client
input.
**Modifications:**
* Delegate simulations discovery to commons library
* Pass configured class name along redefined commons method signatures
* Handle introduced exceptions
* Take advantage of common interface between batch and interactive enterprise plugin

feat: delegate simulation classes discovery to commons and allow simulation start override, closes MISC-357

---

build.gradle
src/main/groovy/io/gatling/gradle/CommonLogMessage.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
src/main/groovy/io/gatling/gradle/RecoverEnterprisePluginException.groovy

chore: centralize plugin exception handling accross tasks
---
Recovering from error is always the same
Add RecoverEnterprisePluginException to extend in order to get recovering method
feat: handle unsupported version exception, closes MISC-374
---
New commons version throw `UnsupportedJavaVersionException` when java version isn't supported by Gatling Enterprise CLoud
Log exception message, along java option to target a compatible bytecode.

feat: handle unsupported version exception, closes MISC-374

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Motivation:
- system props can't be passed in the command line
- env variables can't be passed to the gradle plugin
Modification:
- use new version of the enterprise commons plugin
- system props can be passed as a string in command line
- env variables can be passed as a string, or in the build.gradle file

Pass env variables and system props as string, closes CLOUD-368

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/test/groovy/func/WhenCompileSimulationSpec.groovy
src/test/groovy/helper/GatlingSpec.groovy
src/test/groovy/helper/GatlingUnitSpec.groovy
src/test/groovy/unit/GatlingPluginTest.groovy

Motivation:
Flaky tests and out of scope feature
Modifications:
* Remove automatic maven central configuration
* Display an explicit message when gatling dependencies are not reachable
Result:
Limit scope
Closes gatling/gatling#4259

feat: remove automatic maven central configuration, #4259

---

.github/workflows/test-only.yml

Motivation:
Builds fail day after day without notable causes.
Modifications:
* Remove obsolete arguments (only a common `cache-disabled` exists now)
* Disable cache
Result:
Avoid cache corruption

chore: avoid cache corruption

---

src/main/groovy/io/gatling/gradle/RecoverEnterprisePluginException.groovy

ref: MISC-396
Motivation:
The error message in case of UnsupportedJavaVersionException is not clear enough
Modifications:
In case of UnsupportedJavaVersionException:
- give the full example of the setting to use
- suggest using the newer 'release' setting (available from JDK 10, and this will only apply to users on JDK 18+) rather than  'targetCompatibility'
- also link to the toolchain doc, that's another recommended way to deal with different Java versions on Gradle
Result:
Better information for the user in case of error.

Improve error message in case of Java version error

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy

Since Gradle 7.6, we get a warning that this class will be removed in Gradle 9.0.
https://docs.gradle.org/current/javadoc/org/gradle/util/VersionNumber.html

Remove usage of deprecated import "org.gradle.util.VersionNumber"

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/test/groovy/unit/GatlingPluginTest.groovy

Motivation:
We should only touch the gatling configs.
See https://community.gatling.io/t/scala-library-dependency-leaked/7495

Stop adding scala-library to implementation, close gatling/gatling#4374

---

src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy

enterPrisePLugin was not used, and enterpriseClient not set....
Linked to https://gatlingcorp.atlassian.net/browse/ISC-2177

fix: use correct variable name in enterprise upload task

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/test/groovy/func/GradleCompatibilitySpec.groovy
src/test/groovy/unit/GatlingPluginTest.groovy

Update GatlingPlugin to lazy load and configure tasks
When using the Gatling Gradle plugin in conjunction with Gradle Enterprise, the build scan identified that the Gatling plugin was eagerly loading tasks into the task graph when they did not need to be. This slows down large builds with hundreds of modules and tens of thousands of tasks. Since Gradle 5.0 the concept of [task configuration avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) was added. This helps speed up builds by only registering tasks when they are needed. This commit updates the Gatling plugin to use task configuration avoidance.
Moving to task configuration avoidance is fairly straightforward. There is a guide in the [documentation](https://docs.gradle.org/current/userguide/task_con …

Update GatlingPlugin to lazy load and configure tasks

---

build.gradle
src/main/groovy/io/gatling/gradle/CommonLogMessage.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Configuration example in the `build.gradle`:
```groovy
gatling {
enterprise {
waitForRunEnd true // or waitForRunEnd = true
}
}
```
or run with e.g. `./gradlew gatlingEnterpriseStart -Dgatling.enterprise.waitForRunEnd=true`

feat: Add ability to monitor progress and wait for run end for enterpriseStart

---

src/main/groovy/io/gatling/gradle/LogbackConfigTask.groovy
src/test/groovy/func/WhenRunSimulationSpec.groovy

Motivation:
On Gradle 7.0 to 7.4, the property annotation analysis fails for our task LogbackConfigTask because the logger property isn't annotated as input, output, or internal.
Modifications:
- Annotate LogbackConfigTask#logger as internal
- Add test with several Gradle versions in WhenRunSimulationSpec

fix: LogbackConfigTask crash on Gradle 7.0 to 7.4, close gatling/gatling#4394

---

src/main/groovy/io/gatling/gradle/LogbackConfigTask.groovy
src/test/groovy/func/WhenRunSimulationSpec.groovy
src/test/groovy/unit/LogbackConfigTaskTest.groovy

Motivation:
Currently, LogbackConfigTask crashes on some Gradle versions (crashes on 5.6.4 and 6.4.1, but works on 5.0 or 6.9.1). On those versions, calling LogbackConfigTask#getLogger() leads to an infinite recursive call and a stack overflow error.
Modifications:
- The getLogger override on LogbackConfigTask is only needed for the tests in LogbackConfigTaskTest, so we can cimply remove it without affecting production code.
- In LogbackConfigTaskTest, use reflection to set the private logger field defined in a parent class.
- Add the previously failing Gradle versions to a test in WhenRunSimulationSpec
Result:
- We still need a hack to mock the logger in LogbackConfigTaskTest, but now it's only in the test code, not in the production code
- The plugin works again on the Gradle versions …

fix: LogbackConfigTask crash on some Gradle 5.x/6.x versions

---

src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy

I get this warning
```
compileGatlingScala
[Warn] : -target is deprecated: Use -release instead to compile against the correct platform API.
```
I hope this fixes it.
See 
https://docs.scala-lang.org/overviews/compiler-options/index.html
https://docs.gradle.org/current/userguide/upgrading_version_7.html#scala_compilation_target
https://docs.gradle.org/8.1.1/userguide/scala_plugin.html#sec:scala_target

replace deprecated -target with -release jdk version

---

src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Motivation:
Our users doesn't know about private or public control plane.
Modifications:
Remove private prefix on configuration.

chore: remove "private" prefix from control plane config

---

src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Motivation:
control plane URL is optional but enterprisePackage crash if absent.
Modifications:
Add checks
Result:
No more bug.

fix: check if control plane URL is null before building URL

---

src/main/groovy/io/gatling/gradle/GatlingEnterprisePackageTask.groovy

Motivation:
- grpc-java has two modules that depend on each other, causing circular recursion on the collectDepAndChildren function
Modification:
- stop the recursion if the accumulator already contains a dependency
Result:
- stackoverflowless

fix: packaging breaks on cyclic dependencies

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy

Motivation:
Make Gatling as Code accessible to gradle plugin user
Modifications:
Initialize package ID from settings, overwrite package id by retrieving new package id from json config file if exists.
Ref: MISC-448

feat: load and resolve config file in enterpriseUpload

---

src/main/groovy/io/gatling/gradle/GatlingRunTask.groovy

Motivation:
We don't need to pass the compiled code folder nor the resources one. These files are already in the classpath.

chore: remove useless options passed to Gatling#main

---

src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy

Motivation:
- Package Descriptor feature is going out of beta and v1 is coming
Modifications:
- Remove beta package descriptor deployment call from enterpriseUpload target
Result:
- Beta package descriptor: out

chore: drop beta package descriptor feature, closes HYB-546

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseDeployTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/main/groovy/io/gatling/gradle/RecoverEnterprisePluginException.groovy

**Modifications:**
* Drop unexisting methods
* Integrate new enterprise start depending on deployment

feat: integrate new enterprise start mecanism depending on deployment, closes HYB-569

---

src/main/groovy/io/gatling/gradle/GatlingEnterprisePackageTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy

Motivation:
A previous commit stopped making GatlingEnterprisePackageTask extend the Jar task as it doesn't contain any useful code for use.
But actually, gradle has some hardcoded behavior for this class regarding publishing.
This broke the publishing process documented in the SH documentation (used to publish in a maven repository).

fix: Restore original Enterprise package publishing, close MISC-459

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseDeployTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy
src/main/groovy/io/gatling/gradle/UnsupportedClientPluginException.java

Motivation:
- Interactive & CI envvar detection should be shared in commons plugin library.
Modifications:
- Upgrade commons to 1.9.0-M17
- Use common EnterprisePlugin and BatchEnterprisePlugin instanciation
Result:
- Less logic in maven plugin, more in common !

chore: upgrade plugin-commons to 1.9.0-M17

---

src/main/groovy/io/gatling/gradle/GatlingRecorderTask.groovy

Motivation:
gatlingRecorder depends on logbackTask which is no more present.
Modifications:
Remove all logbackTask reference
Result:
We can launch the recorder again.

fix: fix gatlingRecorder task

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseDeployTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseStartTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Motivation:
- Users want to identify their simulation runs conditions
- Users should be able to set run title and description to add metadata
Modifications:
- Pass run title and description as start operation parameters
Result:
- Run title and description can be set by users at simulation start

feat: set run title and description with enterpriseStart, closes HYB-593

---

src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

Cast exception when setting package or simulation ID from system props.
Use `UUID.fromString` when package or simulation ID is compute from system props.

fix: package and simulation ID from system props, closes HYB-690

---

.github/workflows/publish.yml
.github/workflows/test-only.yml

Motivation:
Action gradle/gradle-build-action is deprecated. See also: https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
Modifications:
Replace with gradle/actions/setup-gradle (to set up Gradle) and a run step (to execute gradlew).

chore: Replace deprecated gradle-build-action with setup-gradle

---

.github/workflows/publish.yml

Motivation:
In YAML, folded-style block scalars (with '>') do not insert new lines... Except when the indentation changes. So we had unexpected new lines separating the parameters from the command.
Modifications:
Use a literal-style block scalar (with '|') and add backslashes to continue the command. At least it's explicit and there is no surprising behavior.
Result:
Parameters are properly passed to the Gradle command when executing the publish workflow.

fix: Fix parameters for Gradle command in publish workflow

---

build.gradle
src/main/groovy/io/gatling/gradle/GatlingEnterpriseDeployTask.groovy
src/main/groovy/io/gatling/gradle/GatlingEnterpriseUploadTask.groovy
src/main/groovy/io/gatling/gradle/GatlingPlugin.groovy
src/main/groovy/io/gatling/gradle/GatlingPluginExtension.groovy

[chore: drop enterprise upload command with expressive message](https://github.com/gatling/gatling-gradle-plugin/commit/9e801734a97d4ac618b6f0d5257d20df5ecd2852)
Command is replaced by enterprise deploy.
Drop command support, when command is called an error message redirect to deploy command documentation.
[chore: handle simulation validation ID on deploy command](https://github.com/gatling/gatling-gradle-plugin/commit/e8b0806875ca4b611468670c1fd776c3a78e7dff)
Validate a given simulation ID have been deployed.
[fix: retrieve API token from configuration when available](https://github.com/gatling/gatling-gradle-plugin/commit/b179c8fadd0c35ad012621c78973f6e6c90530ec)
API Token was configurable but not used (only available …

chore: handle simulation validation ID on deploy command

---

src/main/groovy/io/gatling/gradle/GatlingEnterprisePackageTask.groovy

Execute enterprise package task with `GATLING_ENTERPRISE_BUILDER_PACKAGE_PATH`:
1. Execute the command, file is properly created
2. Delete the file
3. Execute the command, file is not recreated
Disable cache and set up to date to false.
**Result:**
File is always recreated

fix: force gatling enterprise package task execution, closes CLD-7239

---

.github/workflows/build.yml
.github/workflows/release.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/groovy/io/gatling/gradle/GatlingEnterprisePackageTask.groovy
src/test/groovy/func/WhenGroovyRunScalaSimulationSysPropsJvmArgsSpec.groovy
src/test/groovy/helper/GatlingFuncSpec.groovy

Modifications:
* build with Java 21 (highest version supported in our gradle range) but make sure to emit Java 11 bytecode
* build with Gradle 9.1.0
* as we now execute the tests with Java 21, Gatling functional tests need some --add-opens JVM options
* as we now execute the tests with Java 21, Spock needs an --add-opens JVM option
* GatlingEnterprisePackageTask needs to be abstract now

chore: add Gradle 9 to the test matrix
